[[main]]
    name = "Retour au site principal"
    weight = 5
    url = "https://daif1.github.io"

[[main]]
    pre = "pencil"
    name = "Blog"
    pageRef = "posts"
    weight = 10

[[main]]
  pre = "github"
  name = "GitHub"
  url = "https://github.com/DaiF1/"
  weight = 30
