baseURL = 'https://daif1.github.io/blog/'
theme = 'blowfish'
defaultContentLanguage = 'en'

[languages]
    [languages.en]
        contentDir = 'content/en'
    [languages.fr]
        contentDir = 'content/fr'

[markup.goldmark.renderer]
    unsafe=true
